### ISSUE TITLE
How add new version dll to the project?

### ISSUE THREAD

**Issue by pay632006** [SaferSocietyGroup/SleuthkitWrapper#1]
How can I use new version of sleuth kit in this project? I have problem in building dll format from the Sleuth kit develop.

**Comment by johnlundberg** [comment]
Hi pay632006,

We are currently working on updating the wrapper to work with the new sleuthkit version so we should be able to push those changes soon.

**Comment by dhacker9** [comment]
Any update on availability of this?  Seem to be having a problem with libtsk4.dll.

**Comment by eklann** [comment]
We have just updated the wrapper, and it includes version 4.2.0 of libtsk. Also fixed some project configuration issues that might have caused build problems.

**Comment by dhacker9** [comment]
I’m hoping you can assist further.  Back in April I reached out regarding an updated version of the sleuthkit-wrapper project as I was having difficulty building it and was looking for a wrapper that encapsulated TSK4 for an internal project we’re working on.  That was put on the back burner for several months and I’ve recently picked it back up.  I’ve been able to successfully build the sleuthkit-sharp.dll and am able to access some of its functionality in VS2013.  However, I’m receiving an error message when trying to access a DiskImage.  I have a very rudimentary stub program to test the functionality.

  static void Main(string[] args)
        {
            FileInfo fi = new FileInfo(@"c:\tsk\SleuthkitWrapper-master\unit-tests\resources\USB-disk-image-FAT.e01");
            DiskImage di = new DiskImage(fi);
            Console.WriteLine(di.Size.ToString());
            Console.ReadLine();
        }

I can step into the DiskImage procedure until it makes its first call to NativeMethods and then I receive a DLLNotFoundException indicating that it is Unable to Load DLL ‘libtsk4’: The specified module could not be found (Exception from HRESULT: 0x8007007E)

I have, I believe, successfully built the libtsk4.dll file and have added it as a reference to the project and still get this error.  I have built and rebuilt the entire sleuthkit-sharp solution as well as the individual projects using a variety of different settings, have done x86 and x64 options, have made sure to use /CLR switch, etc., as I had quite a bit of problem even getting it into an acceptable format to add as a reference.  I have noticed that when I use the Object Browser on the libtsk4.dll there are no members/methods, etc.  I would have expected there to be something.

I don’t know if it’s an issue with the build or if it’s something I’m doing incorrectly.  Admittedly, while I understand C# and have added numerous managed DLLs, I am a bit at a loss when it comes to porting unmanaged code via a DLL.  Perhaps there’s something else that needs to occur.  I have scoured the internet and can find next to no documentation that has helped.

Any assistance would be greatly appreciated – even if it is to point me to an adequate resource that I can continue my research.

Thanks.
-D

Damon S. Hacker, MBA, CCE CISA
Vestige Digital Investigations
We Turn Digital Evidence into IntelligenceTM
Responsiveness, Speed & Availability | Reliabilty | Knowledge
23 Public Sq., Ste. 250
Medina, OH 44256
330.721.1205
330.721.1206 Fax
dhacker@vestigeltd.com<mailto:dhacker@vestigeltd.com>
www.vestigeltd.com<http://www.vestigeltd.com>

Crain’s Cleveland Business’ 2017 BOOK OF LISTS is published!
Look for Vestige’s Ad<http://www.vestigeltd.com/in-the-news/vestige-ad-2017-crains-cleveland-business-book-lists/>:  Digital Evidence Is All Around Us – it can help win cases!
It includes our FREE Whitepaper Download: Electronic Devices Are Witnesses<http://www.vestigeltd.com/crains-bol-2017/>
Don’t miss it!

**Comment by arcanegame** [comment]
Hi,

You don't need to have the libtsk4.dll as a reference in your C# project. You just need to have it copied to the output directory so that the wrapper can use it. Furthermore you will also need "ewf.net.dll", "libewf.dll",  and "zlib.dll" in your output directory. Hope this helps :)

**Comment by eklann** [comment]
Hi,

You don't need to have the libtsk4.dll as a reference in your C# project. You just need to have it copied to the output directory so that the wrapper can use it. Furthermore you will also need "ewf.net.dll", "libewf.dll", and "zlib.dll" in your output directory. Hope this helps :)

**Comment by dhacker9** [comment]
This still doesn't seem to be the fix.  I've tried several different configurations and hoping you can provide additional support.

1st question -- Does libtsk4.dll need to be build WITH or WITHOUT CLR support (my initial assumption was without -- that it's fully native, which seems to make the most sense).  However, when I build with the /clr option, then I still get the same error I was getting before even when not adding it as a reference, but including it (along with the other DLLs you listed in the output directory.

If I compile it WITH CLR support (/clr option), then it no longer bombs with a "can't find the DLL libtsk4" error which I was getting before, however, then I get a LockLoader error -- which makes sense because of the mixed mode assembly that seems to be out-of-sorts -- hence, having me go back and change it back to without CLR support.

The specific location that it is crashing is

 this._handle = NativeMethods.tsk_img_open_sing(this.files[0].FullName, 0, 0);
in the private void Init(IEnumerable<FileInfo> _files) function.

As soon as it executes this line, I receive a System.DllNotFoundException in sleuthkit-sharp.dll -- "Unable to load DLL 'libtsk4':  The specified module could not be found.  (Exception from HRESULT: 0x8007007E).


I seem to be in a circular issue.  I'm using VS2013 with (v120) platform toolset.

Any thoughts?

-D

Damon S. Hacker, MBA, CCE, CISA
Vestige Digital Investigations
We Turn Digital Evidence into Intelligence(TM)
23 Public Sq., Ste. 250
Medina, OH 44256
dhacker@vestigeltd.com
www.VestigeLtd.com
________________________________

**Comment by eklann** [comment]
Sorry for the late response, 

1. We build without /clr just as it is configured in the repo.

2. The error message still indicates that your problem is that the libtsk4.dll is missing from your output directory. Make sure to copy the following dlls to the output directory (the one that you are running your program from):
- libtsk4.dll
- ewf.net.dll
- libewf.dll
- zlib.dll
